
def error_module(p_error_no,p_module_name,p_exp):
        print('')
        print('Error No    : '+p_error_no)
        print('Module      : '+p_module_name)
        print('Explanation : '+p_exp)
        print('')

def commands(args):
        print(' You can use below commands')
        print(" ")
        print(' ORACLE Commands ')
        print(" ")
        print(' --> ora_chk ')
        print(' --> ora_sid  ')
        print(' --> ora_brute ')
        print(' --> ora_brute_file  ')
        print(" ")
        print(' MSSQL Commands ')
        print(" ")
        print(' --> mssql_chk_browser   ')
        print(' --> mssql_chk_odbc   ')
        print(' --> mssql_brute ')
        print(' --> mssql_brute_file ')
        print(' --> mssql_brute_null_passwd')
        print(" ")
